### ISSUE TITLE
关于图片加载

### ISSUE THREAD

**Issue by agni-bumi** [cssxsh/weibo-helper#27]
因为有的用户可能一次发送大量图片，会造成过多负载；
    又或者用户发的的九宫拼贴图，加载全部图片的意义不大。
所以希望可以增加图片输出格式一个设置

NO_IMAGE | 不输出图片
FIRST_IMAGE | 最多输出一张图片
ALL_IMAGE | 输出所有图片

（顺便感谢一下这个插件的制作，帮了我这些外行人大忙了，因为微博插件似乎没什么人用）

**Comment by cssxsh** [comment]
with https://github.com/cssxsh/weibo-helper/releases/tag/v1.2.0

**Comment by agni-bumi** [comment]
感谢这么快回复，不过测试了后发现只能输出指定数量内的图片，如果超过就1张也不显示了，我是想着能预览1张来判断这篇消息的内容

**Comment by agni-bumi** [comment]
或者增加截图模式？

**Comment by cssxsh** [comment]
> 或者增加截图模式？

截图成本太高了

**Comment by agni-bumi** [comment]
> > 或者增加截图模式？
> 
> 截图成本太高了

🤔不能像B站插件一样吗？如果不行那就算了吧

**Comment by cssxsh** [comment]
> > > 或者增加截图模式？
> > 
> > 
> > 截图成本太高了
> 
> 🤔不能像B站插件一样吗？如果不行那就算了吧

可以是可以，但是微博截图的效果并不好

**Comment by FlandiaYingman** [comment]
有没有可能通过使用微博的 css 来模仿真实的截图？

**Comment by cssxsh** [comment]
with 1.4.7
