### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ArbETaperingsky** [cssxsh/weibo-helper#37]
![Screenshot_2022-03-09-23-29-15-57_846b44643ec609f507828878741e1f9a.jpg](https://user-images.githubusercontent.com/44714368/157473886-458b2fa2-35a7-48aa-ad64-84d374fc5f01.jpg)

**Comment by cssxsh** [comment]
请升级mirai版本

**Comment by ArbETaperingsky** [comment]
[92m2022-03-07 09:43:51 I/MiraiNative: 当前系统: Linux[0m[m
[92m2022-03-07 09:43:51 I/MiraiNative: 当前架构: amd64[0m[m
[92m2022-03-07 09:43:51 I/plugin: Successfully loaded plugin MiraiNative v2.0.5-cp

**Comment by ArbETaperingsky** [comment]
[K[92m2022-03-07 09:44:01 I/MiraiNative: [DiceDriver DiceDriver] Dice! by 溯洄 & Shiki Ver 2.6.3beta4(603) [GNUC 8.4.0 Feb  6 2022 05:55:07 on
Dice!驱动器 by 安研色Shiki & 溯洄w4123 ver0.2.1(3)[2021-08-08 06:46:17] for CoolQ[0m[m
>

**Comment by cssxsh** [comment]
2022-03-10 10:50:07 I/main: Starting mirai-console...
2022-03-10 10:50:07 I/main: Backend: version `2.10.1`, built on 2022-03-08 21:54:56.
2022-03-10 10:50:07 I/main: Frontend Terminal: version `2.10.1`, provided by Mamoe Technologies

这个 2.10.1 才是 mirai (mirai-console) 的版本

**Comment by ArbETaperingsky** [comment]
[92m2022-03-07 09:43:51 I/main: Starting mirai-console...[0m[m
[92m2022-03-07 09:43:51 I/main: Backend: version 2.8.2, built on 2021-11-20 00:35:26.[0m[m
[92m2022-03-07 09:43:51 I/main: Frontend Terminal: version 2.8.2, provided by Mamoe Technologies[0m[m
[

2.82

**Comment by ArbETaperingsky** [comment]
好像mirai版本和dice版本是不匹配的，但我还是这样将就用了，不知道是不是这个缘故，其他的*-helper插件也不能用

**Comment by cssxsh** [comment]
请使用更新版本的mirai

**Comment by ArbETaperingsky** [comment]
> 请使用更新版本的mirai
> Mirai（core，console） 版本， 不是 MiraiNative  版本

10.3
