### ISSUE TITLE
重复转发旧微博

### ISSUE THREAD

**Issue by saltfish13** [cssxsh/weibo-helper#41]
net.mamoe:mirai-console" v2.11.0-RC2
net.mamoe:mirai-console-terminal" v2.11.0-RC2
net.mamoe:mirai-core-all v2.11.0-RC2

也没什么报错就是一直在转发之前的微博，从最新的一直转发到最旧的

**Comment by saltfish13** [comment]
1.4.15

**Comment by saltfish13** [comment]
之后添加完关注后的那一次轮询会发微博（转发新的和旧的），之后控制台就不显示轮询了，然后新的微博也不转发了（好像我一直再提类似的issue幸苦您了
![%I6HP6J1E G~ MS5L1EZ{CE](https://user-images.githubusercontent.com/59356579/168480565-4fc2aa6b-64cc-475a-89a7-7d4a560eb39d.png)
)

**Comment by cssxsh** [comment]
with https://github.com/cssxsh/weibo-helper/releases/tag/v1.4.16

**Comment by cssxsh** [comment]
with https://github.com/cssxsh/weibo-helper/releases/tag/v1.4.16

**Comment by saltfish13** [comment]
重新安装了1.4.16之后重新添加推送任务后虽然log显示轮询完成但是发现不了新发微博进而也没推送。
