### ISSUE TITLE
能在配置里开放更细致的 filter 开关吗

### ISSUE THREAD

**Issue by kuronekonano** [cssxsh/weibo-helper#47]
发现其实 weibo api 是能看到被监控用户点赞过的微博？能麻烦暴露到配置文件里吗，想被推送这类信息 ![image](https://user-images.githubusercontent.com/33979917/224671960-95a963d2-1ef8-401a-af2d-3ff97b851339.png)

**Comment by cssxsh** [comment]
着急使用可以到这里下载

https://github.com/cssxsh/weibo-helper/actions/runs/4403978968

**Comment by kuronekonano** [comment]
好家伙，大佬太快了，感谢
