### ISSUE TITLE
在监听聊天消息中的微博链接时权限验证失败

### ISSUE THREAD

**Issue by Polar-Pumpkin** [cssxsh/weibo-helper#49]
通过有 Context 的权限组继承权限时验证失败

![image.png](https://s2.loli.net/2023/09/07/GxpfboLw14OWtuy.png)

直接给予权限时验证失败

![image.png](https://s2.loli.net/2023/09/07/12rPfXObwZkC4pA.png)

运行的是我修改过代码的编译，仅修改输出更多信息以供调试

![image.png](https://s2.loli.net/2023/09/07/zGXUYVLA2TnytW8.png)

我自己账号发微博链接就能正常验证通过，但是群友不行，不知道为什么

**Comment by cssxsh** [comment]
你好像并不会使用 LuckPerms

**Comment by Polar-Pumpkin** [comment]
😔原来Mirai Console的权限ID使用冒号，在LuckPerms上要换成点。

总之谢谢您提醒我
